### ISSUE TITLE
Kobo Proxying fails on new Kobo update v4.43.23418

### ISSUE THREAD

**Issue by reubensinha** [gotson/komga#2063]
### Steps to reproduce

1. Enable Proxy Kobo Sync requests to Kobo Store
2. Tap Sync on Kobo

### Expected behavior

Proper Sync

### Actual behavior

Sync Failed. Please try again.

### Logs

```
big-bear-komga  | 2025-08-28T00:31:02.406-07:00  INFO 1 --- [io-25600-exec-5] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
big-bear-komga  |  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
big-bear-komga  | 
big-bear-komga  | java.lang.IllegalArgumentException: Invalid character found in the request target [/kobo/d733a3f8e0f24842a514c37d133e2ff3/v1/assets?DiffRequests=[%7BKey:EPD-KoboPlus-ReadOnly-NeverSubscribed,ETag:%7D] ]. The valid characters are defined in RFC 7230 and RFC 3986
big-bear-komga  | 	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:478) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:903) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1769) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1189) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:658) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.43.jar:10.1.43]
big-bear-komga  | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na][](url)
```

### Komga version

v1.23.3-master

### Operating system

Ubuntu 25.04 x86_64

### Installation method

Docker

### Other details

Attempted to add SERVER_TOMCAT_RELAXED_QUERY_CHARS: "[,]" to environment variables, which gave a different error.
Proxied Request: /kobo/<key>/v1/assets?DiffRequests=[{Key:EPD-KoboPlus-ReadOnly-NeverSubscribed,ETag:}]

Error:
```
java.lang.IllegalArgumentException: Not enough variable values available to expand 'Key'
    at org.springframework.web.util.UriComponents$VarArgsTemplateVariables.getValue(UriComponents.java:370)
    ...
    at org.gotson.komga.infrastructure.kobo.KoboProxy.proxyCurrentRequest(KoboProxy.kt:88)
```

### Acknowledgements

- [x] I have searched the existing issues (open AND closed) and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have checked the [FAQ](https://komga.org/docs/faq).
- [x] I have updated the app to the latest version.
- [x] I will fill out all of the requested information in this form.

**Comment by gotson** [comment]
it's a Kobo problem, somehow they cannot implement basic HTTP requests. Duplicate of #2056

**Comment by gotson** [comment]
I've fixed this issue `java.lang.IllegalArgumentException: Not enough variable values available to expand 'Key'`

**Comment by obynio** [comment]
Ah yes was facing a similar issue, proxying was failing, glad it will be fixed in the next release

**Comment by eleith** [comment]
i'm on `1.23.4` and Kobo Software `4.38.23429` and i still getting the following error:

```
java.lang.IllegalArgumentException: Invalid character found in the request target [/kobo/{some-long-hash}/v1/assets?DiffRequests=[%7BKey:EPD-KoboPlus-ReadOnly-NeverSubscribe
d,ETag:W/NjM4MjU4OTA5NzgwMDAwMDAwLTMwMjQ1%7D] ]. The valid characters are defined in RFC 7230 and RFC 3986
```

i can open up a new ticket, but figured i would start with this report, in case there are further actions i need to take beyond updating Komga.

**Comment by gotson** [comment]
> i'm on `1.23.4` and Kobo Software `4.38.23429` and i still getting the following error:
> 
> ```
> java.lang.IllegalArgumentException: Invalid character found in the request target [/kobo/{some-long-hash}/v1/assets?DiffRequests=[%7BKey:EPD-KoboPlus-ReadOnly-NeverSubscribe
> d,ETag:W/NjM4MjU4OTA5NzgwMDAwMDAwLTMwMjQ1%7D] ]. The valid characters are defined in RFC 7230 and RFC 3986
> ```
> i can open up a new ticket, but figured i would start with this report, in case there are further actions i need to take beyond updating Komga.


it's still a Kobo problem, their HTTP request is invalid according to HTTP standards. If you have a reverse proxy in front, maybe the reverse proxy is less strict that Komga's webserver, and it would work.

Else if you connect to Komga directly you would need to relax the webserver as indicated in the first message of the thread:

> add `SERVER_TOMCAT_RELAXED_QUERY_CHARS: "[,]"` to environment variables

**Comment by eleith** [comment]
i can confirm that adding `SERVER_TOMCAT_RELAXED_QUERY_CHARS: "[,]"` as an environment variable to my `docker-compose.yml` now works with `1.23.4`

thanks for the clarification

**Comment by gotson** [comment]
> i can confirm that adding `SERVER_TOMCAT_RELAXED_QUERY_CHARS: "[,]"` as an environment variable to my `docker-compose.yml` now works with `1.23.4`
> 
> thanks for the clarification

thanks for confirming, i will add this to the documentation

**Comment by gotson** [comment]
https://komga.org/docs/guides/kobo/#sync-fails-with-invalid-character-found-in-the-request-target

**Comment by reubensinha** [comment]
It's now running into an issue of "Failed to get response from Kobo /v1/initialization". All the other Kobo endpoints seem to be proxying correctly, it's just this one that fails, which of course causes the entire sync to fail.

Thanks for all your work!

Logs:

```
big-bear-komga | 2025-09-11T11:25:16.647-07:00 DEBUG 1 --- [io-25600-exec-9] o.g.komga.infrastructure.kobo.KoboProxy : Proxy URL: https://storeapi.kobo.com/v1/affiliate?PlatformID=00000000-0000-0000-0000-000000000390&SerialNumber=[REDACTED]
big-bear-komga | 2025-09-11T11:25:16.649-07:00 DEBUG 1 --- [io-25600-exec-9] o.g.komga.infrastructure.kobo.KoboProxy : Headers out: [accept:"application/json", authorization:"Bearer [REDACTED]", user-agent:"Mozilla/5.0 (Linux; U; Android 2.0; en-us;) AppleWebKit/538.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/538.1 (Kobo Touch 0390/4.43.23418)", accept-language:"en-US, *;q=0.9"] 

big-bear-komga | 2025-09-11T11:25:16.851-07:00 DEBUG 1 --- [io-25600-exec-3] o.g.komga.infrastructure.kobo.KoboProxy : Proxy URL: https://storeapi.kobo.com/v1/initialization big-bear-komga | 2025-09-11T11:25:16.853-07:00 DEBUG 1 --- [io-25600-exec-3] o.g.komga.infrastructure.kobo.KoboProxy : Headers out: [accept:"application/json", authorization:"Bearer [REDACTED]", user-agent:"Mozilla/5.0 (Linux; U; Android 2.0; en-us;) AppleWebKit/538.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/538.1 (Kobo Touch 0390/4.43.23418)", accept-language:"en-US, *;q=0.9"] 
big-bear-komga | 2025-09-11T11:25:16.941-07:00 WARN 1 --- [io-25600-exec-3] o.g.k.i.api.kobo.KoboController : Failed to get response from Kobo /v1/initialization, fallback to noproxy
```

**Comment by eleith** [comment]
@reubensinha i have proxying to the kobo store disabled on my server. i think when i turned it off, then syncing worked for me again.

**Comment by gotson** [comment]
> It's now running into an issue of "Failed to get response from Kobo /v1/initialization". All the other Kobo endpoints seem to be proxying correctly, it's just this one that fails, which of course causes the entire sync to fail.
> 
> Thanks for all your work!
> 
> Logs:
> 
> ```
> big-bear-komga | 2025-09-11T11:25:16.647-07:00 DEBUG 1 --- [io-25600-exec-9] o.g.komga.infrastructure.kobo.KoboProxy : Proxy URL: https://storeapi.kobo.com/v1/affiliate?PlatformID=00000000-0000-0000-0000-000000000390&SerialNumber=[REDACTED]
> big-bear-komga | 2025-09-11T11:25:16.649-07:00 DEBUG 1 --- [io-25600-exec-9] o.g.komga.infrastructure.kobo.KoboProxy : Headers out: [accept:"application/json", authorization:"Bearer [REDACTED]", user-agent:"Mozilla/5.0 (Linux; U; Android 2.0; en-us;) AppleWebKit/538.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/538.1 (Kobo Touch 0390/4.43.23418)", accept-language:"en-US, *;q=0.9"] 
> 
> big-bear-komga | 2025-09-11T11:25:16.851-07:00 DEBUG 1 --- [io-25600-exec-3] o.g.komga.infrastructure.kobo.KoboProxy : Proxy URL: https://storeapi.kobo.com/v1/initialization big-bear-komga | 2025-09-11T11:25:16.853-07:00 DEBUG 1 --- [io-25600-exec-3] o.g.komga.infrastructure.kobo.KoboProxy : Headers out: [accept:"application/json", authorization:"Bearer [REDACTED]", user-agent:"Mozilla/5.0 (Linux; U; Android 2.0; en-us;) AppleWebKit/538.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/538.1 (Kobo Touch 0390/4.43.23418)", accept-language:"en-US, *;q=0.9"] 
> big-bear-komga | 2025-09-11T11:25:16.941-07:00 WARN 1 --- [io-25600-exec-3] o.g.k.i.api.kobo.KoboController : Failed to get response from Kobo /v1/initialization, fallback to noproxy
> ```

don't comment for something unrelated on closed issues.
