### ISSUE TITLE
moving sql database (temporarily) didn't allow it to be detected

### ISSUE THREAD

**Issue by YouthfulRicker** [gotson/komga#863]
### Steps to reproduce

1. Launch Komga,
2. Move your `.komga` folder somewhere else, 
3. Close Komga, 
4. Move the folder back, 
5. Launch Komga again.

### Expected behavior

I accidentally moved the `.komga` folder to my external hard-drive due to an accidental drag (while komga was running). Because of this, I suspected that this is just a simple case of 'put the folder back and voila,' BUT NOOOOO~

### Actual behavior

Essentially what this managed to do, was somehow remove everything. Despite the sqlite file still remaining intact, there were no users, my two libraries had disappeared. It was as is I had gone back in time to when I first downloaded it. 

Oddly enough, the data in the folder is all the same, but the actual web-ui tells me to create a user and add libraries, as if this is a new install.

After a day of leaving komga running, the folder is the exact same as before I moved it. There isn't any new log, and the database file remains untouched. But komga is still not detecting/using it.

### Logs

The following is a paste consisting of the log since the first line from the unfortunate movement of the folder:

> [komga.log](https://pastebin.com/Vqi0naQM)

### Komga version

0.153.1

### Operating system

MacOS Big Sur (not docker)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I have checked the [FAQ](https://komga.org/faq/).
- [X] I have updated the app to the latest version.
- [X] I will fill out all of the requested information in this form.

Sidenote: I still love komga 😅

**Comment by gotson** [comment]
You mention Kavita, this is komga. You also don't explain what the symptoms are. "killed my server" doesn't mean much.

**Comment by YouthfulRicker** [comment]
> You mention Kavita, this is komga. You also don't explain what the symptoms are. "killed my server" doesn't mean much.

Oh, sorry! 
I'll fix the kavita mix-up, and add more detail.

**Comment by billsargent** [comment]
Check your directory permissions. Your log gives you hints about stuff to look at. Theres a file not found error for Journal.

**Comment by YouthfulRicker** [comment]
> Check your directory permissions. Your log gives you hints about stuff to look at. Theres a file not found error for Journal.

Thanks! But the log excerpt which I attached was of Komga suffering after I moved the folder. The main problem is that, when I put it back, it didn't continue as normal, instead acting like a new install. I'll try to make the issue clearer, sorry!

**Comment by YouthfulRicker** [comment]
### Fixed!

> I created an `application.yml` file using the sample in the Komga documentation. Here is the file:

```
GNU nano 2.0.6                                                        File: komga-0.154.0/application.yml                                                                                                              Modified  
# Only keep lines that are relevant to you!
# Lines starting with # are comments
# Make sure indentation is correct (2 spaces at every indentation level), yaml is very sensitive!
komga:
#  libraries-scan-cron: "0 0 */8 * * ?"  # periodic scan every 8 hours
#  libraries-scan-cron: "-"# disable periodic scan
libraries-scan-startup: true# scan libraries at startup
#  libraries-scan-directory-exclusions:  # patterns to exclude directories from the scan
#    - "#recycle" # synology NAS recycle bin
#    - "@eaDir"   # synology NAS index/metadata folders
#    - "@Recycle" # QNAP NAS recycle bin
remember-me:
key: Komga-Cookie!    # required to activate the remember-me auto-login via cookies
validity: 30d     # validity of the cookie in seconds, here 30 days
session-timeout: 7d # session timeout, here 7 days
database:
file: /Users/[your-user]/.komga/database.sqlite
#  native-webp: true
cors.allowed-origins:
- http://localhost:8057
- http://localhost:8058
delete-empty-collections: true
delete-empty-read-lists: true
server:
port: 8056
#  servlet.context-path: /komga
```

> I commented out the `libraries-scan-cron` options because java gave me an error saying there were two instances that clashed. and the `servlet.content.path` because I need to take a deep dive into my system files to find it. ATM, komga is working exactly like before now!

**Comment by YouthfulRicker** [comment]
## Fixed! (almost)

I created an `application.yml` file containing the following:

```  
# Only keep lines that are relevant to you!
# Lines starting with # are comments
# Make sure indentation is correct (2 spaces at every indentation level), yaml is very sensitive!
komga:
#  libraries-scan-cron: "0 0 */8 * * ?"  # periodic scan every 8 hours
#  libraries-scan-cron: "-"# disable periodic scan
libraries-scan-startup: true# scan libraries at startup
#  libraries-scan-directory-exclusions:  # patterns to exclude directories from the scan
#    - "#recycle" # synology NAS recycle bin
#    - "@eaDir"   # synology NAS index/metadata folders
#    - "@Recycle" # QNAP NAS recycle bin
remember-me:
key: Komga-Cookie!    # required to activate the remember-me auto-login via cookies
validity: 30d     # validity of the cookie in seconds, here 30 days
session-timeout: 7d # session timeout, here 7 days
database:
file: /Users/antariksh/.komga/database.sqlite
#  native-webp: true
cors.allowed-origins:
- http://localhost:8057
- http://localhost:8058
delete-empty-collections: true
delete-empty-read-lists: true
server:
port: 8056
#  servlet.context-path: /Users/antariksh/.komga
```

I've commented out the `libraries-scan-cron` because it gave me numerous errors about there being two instances of the same command colliding with different cron times, so I'll try to investigate that soon.
And I've commented out `servlet.content.path` as well because I need to take a deeper dive into my computer to figure out where komga's reading it from 😅.

**Comment by gotson** [comment]
Not sure what you are trying to do, but the issue is still incorrect (still mentions Kavita in the title), and it's still not clear what you have done to trigger the situation, not what you have been doing to try and correct it.

Provided logs are not helpful either, as they don't start from the application startup.

Komga's config directory contains the database as well as other files, though only the database is critical. If the database is not there, then it's considered to be a fresh install, starting from scratch.

You can restore a database that was moved somewhere else, that's how people do backup of Komga's data, but Komga must be stopped when doing so.
